### ISSUE TITLE
Missing pause button after game reset

### ISSUE THREAD

**Issue by JBYoshi** [JBYoshi/BlockDodge#12]
```
Exception in thread "main" java.lang.NullPointerException
        at jbyoshi.blockdodge.gui.InputInGame.playerDied(InputInGame.java:172)
        at jbyoshi.blockdodge.PlayerDodgeShape.onDeath(PlayerDodgeShape.java:40)
        at jbyoshi.blockdodge.BlockDodgeGame.remove(BlockDodgeGame.java:42)
        at jbyoshi.blockdodge.DodgeShape.explode(DodgeShape.java:97)
        at jbyoshi.blockdodge.DodgeShape.onCollided(DodgeShape.java:101)
        at jbyoshi.blockdodge.BlockDodgeGame.go(BlockDodgeGame.java:100)
        at jbyoshi.blockdodge.gui.BlockDodge.main(BlockDodge.java:88)
```

**Comment by JBYoshi** [comment]
Okay, it's not because of using the arrow keys... it's because the pause button is not being re-added after resetting.
